In [ ]:
# -*- coding: utf-8 -*-

#Regresion Logistica

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(r"C:\Users\user\Documents\PYTHON\Python data science y big data\Datos\Indicators_of_Health_Insurance_Coverage.csv",nrows=1e5)


In [2]:
df = df.dropna(subset=['Low CI','Group'])
df = df.sample(frac=1).head(1000)
Y = df[['Group']]
X = df[['Low CI']]

In [3]:
LogisticRegression(solver='lbfgs', max_iter=10000)
logreg = LogisticRegression()
model = logreg.fit(X, Y.values.ravel())
Y_pred = logreg.predict(X)
#no es el numero de iteraciones, toca averiguar como mas lo puedo solucionar--> el error puede ser que no es una dummy 

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
np.round(logreg.predict_proba(X),3)
#arroja las probabilidades que dice el modelo, osea para el todos los casos dicen cual es la probabilidad de que este en cualquiera
#de las categorias 

array([[0.058, 0.005, 0.057, ..., 0.007, 0.752, 0.033],
       [0.048, 0.01 , 0.056, ..., 0.008, 0.768, 0.013],
       [0.047, 0.01 , 0.055, ..., 0.008, 0.767, 0.012],
       ...,
       [0.046, 0.011, 0.055, ..., 0.008, 0.765, 0.011],
       [0.046, 0.01 , 0.055, ..., 0.008, 0.766, 0.012],
       [0.048, 0.009, 0.056, ..., 0.007, 0.768, 0.014]])

In [ ]:
#Con este comando evaluamos la eficiencia del modelo (cuando coinciden las predicciones con el valor real) entre mas cerca a 1
#mejor predice los datos el modelo 
np.mean(Y_pred==Y)
#No corro esta linea ya que debido al problema en la linea 3, ConvergenceWarning: lbfgs failed to converge (status=1):
#STOP: TOTAL NO. of ITERATIONS REACHED LIMIT. no va a dar lo que necesitamos que es solo un numero 

In [6]:
np.mean(Y)

Series([], dtype: float64)

In [5]:
confusion_matrix = confusion_matrix(Y,Y_pred)
print(confusion_matrix)

[[  0   0   0   0   0   0   0  50   0]
 [  0   0   0   0   0   0   0   8   0]
 [  0   0   0   0   0   0   0  54   0]
 [  0   0   0   0   0   0   0   2   0]
 [  0   0   0   0   0   0   0  73   0]
 [  0   0   0   0   0   0   0  24   0]
 [  0   0   0   0   0   0   0   6   0]
 [  0   0   0   0   0   0   0 762   0]
 [  0   0   0   0   0   0   0  21   0]]
