In [ ]:
# -*- coding: utf-8 -*-

#PREPROCESAMIENTO DE DATOS

In [3]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\user\Documents\PYTHON\Python data science y big data\Datos\Indicators_of_Health_Insurance_Coverage.csv",nrows=1000000)
df = df[['Low CI','High CI','Value']].dropna()

In [4]:
X_scaled = preprocessing.scale(df)
X_scaled
#Crea un arreglo de valores alrededor de 0--> cambia la escala de los datos con centro en 0 y desviacion de 1

array([[-0.76349646, -0.97867361, -0.86566607],
       [-0.68833402, -0.68908232, -0.68675046],
       [-0.63822573, -0.81119913, -0.71832381],
       ...,
       [ 1.09766874,  1.4113268 ,  1.27430489],
       [ 1.70254742,  1.66951663,  1.69177463],
       [ 1.49853509,  1.57880129,  1.55144867]])

In [5]:
X_scaled.mean(axis=0)

array([ 9.54389168e-17,  5.34457934e-17, -2.59593854e-16])

In [6]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [7]:
df.iloc[2]
#vemos los datos para la fila 2(sea una persona, una empresa, un pais)
#No podemos interpretar si los datos de las variables estan en diferentes escalas

Low CI     15.6
High CI    18.1
Value      16.8
Name: 2, dtype: float64

In [9]:
X_scaled[2]
#sabemos que todos los datos de esta fila estan por debajo de la media

array([-0.63822573, -0.81119913, -0.71832381])

In [10]:
min_max_scaler = preprocessing.MinMaxScaler([0,10])
#Aqui se especifica en que rango quiero que quede la escala
X_train_minmax = min_max_scaler.fit_transform(df)
#usando el objeto en la escala que queremos, le damos el comando de que se adapte usando el dataframe
X_train_minmax 
#este tipo de preprocesamiento altera la escala de las variables--> si hay muchos outliers puede ser un problema

array([[1.30054645, 1.13268608, 1.27192982],
       [1.53005464, 2.02804746, 1.83114035],
       [1.68306011, 1.65048544, 1.73245614],
       ...,
       [6.98360656, 8.52211435, 7.96052632],
       [8.83060109, 9.32038835, 9.26535088],
       [8.20765027, 9.0399137 , 8.82675439]])

In [11]:
#Transformar variables categoricas en variable dummy
df = pd.read_csv(r"C:\Users\user\Documents\PYTHON\Python data science y big data\Datos\Indicators_of_Health_Insurance_Coverage.csv",nrows=100)
pd.get_dummies(df['Group'])
#Extrae dummies de una columna--> consume mucha memoria

By Age  By Education  By Race/Hispanic ethnicity  By Sex  By State  \
0        0             0                           0       0         0   
1        1             0                           0       0         0   
2        1             0                           0       0         0   
3        1             0                           0       0         0   
4        1             0                           0       0         0   
..     ...           ...                         ...     ...       ...   
95       0             0                           0       0         1   
96       0             0                           0       0         1   
97       0             0                           0       0         1   
98       0             0                           0       0         1   
99       0             0                           0       0         1   

    National Estimate  
0                   1  
1                   0  
2                   0  
3                   0  
4                   0  
..                ...  
95                  0  
96                  0  
97                  0  
98                  0  
99                  0  

[100 rows x 6 columns]