In [1]:
# -*- coding: utf-8 -*-
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones
#3 clientes califican 4 productos diferentes

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [5]:
valoraciones[0][1]
valoraciones[0,1]
#Escoge el valor que se encuentra en la interseccion entre primera fila(0) y la segunda columna(1)
#Este 7 es la valoracion que le dió el cliente 1 al producto numero 2 

7

In [7]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])
#3 clientes califican en 2 años diferentes(1.2020,2.2021), 4 productos

In [8]:
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [11]:
valoraciones2[1,0,3]
#El cliente 2 en el año 2020 caifica el producto 4 con un puntaje de 4

4

In [12]:
np.zeros((3,2,4))
#Array de solo ceros con las dimensiones especificaddas

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
valoraciones2 + np.ones((3,2,4))
#A la matriz le sumo una matriz de unos

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [14]:
np.mean(valoraciones2)

6.458333333333333

In [15]:
np.mean(valoraciones2, axis = 0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [16]:
np.mean(valoraciones2, axis = 1)

array([[5. , 6. , 6.5, 3.5],
       [5. , 7.5, 7.5, 4. ],
       [9. , 8.5, 9.5, 5.5]])

In [17]:
np.mean(valoraciones2, axis = 2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [18]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))
#Cambia una lista en una matriz con las dimensiones especificadas

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.median(df["columna"])
#mediana de una columna de un dataframe

In [20]:
np.random.rand(2,2)

array([[0.68389475, 0.32713323],
       [0.20725759, 0.07521593]])